# Generated by Django 6.1.2 on 2026-10-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danceclass',
            options={'verbose_name': 'танцевальное занятие', 'verbose_name_plural': 'Танцевальные занятия'},
        ),
        migrations.AlterModelOptions(
            name='dancestyle',
            options={'verbose_name': 'танцевальный стиль', 'verbose_name_plural': 'Танцевальные стили'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('last_name',), 'verbose_name': 'хореограф', 'verbose_name_plural': 'Хореографы'},
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dance_classes', to='dance_school.teacher', verbose_name='Хореограф'),
        ),
    ]
